In [19]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

import joblib

In [20]:
# Load ML-ready dataset
ml_data = pd.read_csv("data/processed/ml_ready_data.csv")

print("Shape:", ml_data.shape)
print(ml_data.columns)
ml_data.head()

Shape: (8037, 7)
Index(['date', 'state', 'district', 'pincode', 'age_0_5', 'age_5_17',
       'age_18_greater'],
      dtype='object')

,date,state,district,pincode,age_0_5,age_5_17,age_18_greater
0,2025-01-09,Maharashtra,Pune,410504,3,0,0
1,2025-01-09,Maharashtra,Pune,411002,1,0,0
2,2025-01-09,Maharashtra,Pune,411003,1,1,0
3,2025-01-09,Maharashtra,Pune,411004,1,0,0
4,2025-01-09,Maharashtra,Pune,411006,1,0,0

In [29]:
import pandas as pd

df = pd.read_csv("data/processed/ml_ready_data.csv")
print(df.columns.tolist())

['date', 'state', 'district', 'pincode', 'age_0_5', 'age_5_17', 'age_18_greater']

In [30]:
# ===============================
# 2. CREATE GAP FEATURE (RUN HERE)
# ===============================

ml_data['gap_5_17'] = (
    ml_data['age_5_17'] /
    (ml_data['age_18_greater'] + 1)
)

display(
    ml_data[['age_5_17', 'age_18_greater', 'gap_5_17']].head()
)

   age_5_17  age_18_greater  gap_5_17
0         0               0       0.0
1         0               0       0.0
2         1               0       1.0
3         0               0       0.0
4         0               0       0.0

In [31]:
# ===============================
# 3. CREATE PROPER RISK SCORE
# ===============================

ml_data['risk_score_5_17'] = (
    ml_data['age_5_17'] /
    (
        ml_data['age_0_5'] +
        ml_data['age_5_17'] +
        ml_data['age_18_greater'] +
        1
    )
)

display(
    ml_data[['age_0_5', 'age_5_17', 'age_18_greater', 'risk_score_5_17']].head(10)
)

   age_0_5  age_5_17  age_18_greater  risk_score_5_17
0        3         0               0         0.000000
1        1         0               0         0.000000
2        1         1               0         0.333333
3        1         0               0         0.000000
4        1         0               0         0.000000
5        1         0               0         0.000000
6        2         1               0         0.250000
7        4         6               1         0.500000
8        2         3               0         0.500000
9        3         5               0         0.555556

In [32]:
# ===============================
# 4. ASSIGN RISK LEVELS
# ===============================

def risk_label(score):
    if score >= 0.5:
        return "High Risk"
    elif score >= 0.25:
        return "Medium Risk"
    else:
        return "Low Risk"

ml_data['risk_level_5_17'] = ml_data['risk_score_5_17'].apply(risk_label)

display(
    ml_data[['risk_score_5_17', 'risk_level_5_17']].head(10)
)

   risk_score_5_17 risk_level_5_17
0         0.000000        Low Risk
1         0.000000        Low Risk
2         0.333333     Medium Risk
3         0.000000        Low Risk
4         0.000000        Low Risk
5         0.000000        Low Risk
6         0.250000     Medium Risk
7         0.500000       High Risk
8         0.500000       High Risk
9         0.555556       High Risk

In [33]:
# ==============================
# FINAL CELL: Save Risk Scores
# ==============================

ml_data.to_csv(
    "data/processed/final_risk_scores.csv",
    index=False
)

print("Final risk dataset saved successfully")

Final risk dataset saved successfully

In [34]:
from pathlib import Path

# Get project root (aadhaar-enrollment)
BASE_DIR = Path.cwd().parent

OUTPUT_PATH = BASE_DIR / "data" / "processed"
OUTPUT_PATH.mkdir(parents=True, exist_ok=True)

ml_data.to_csv(
    OUTPUT_PATH / "final_risk_scores.csv",
    index=False
)

print("Saved to:", OUTPUT_PATH / "final_risk_scores.csv")

Saved to: c:\Users\Pragya\Desktop\uidai-hackathon\aadhaar-enrollment\data\processed\final_risk_scores.csv

In [35]:
import os
print("Current working directory:")
print(os.getcwd())

Current working directory:
c:\Users\Pragya\Desktop\uidai-hackathon\aadhaar-enrollment\notebooks